export const copy = {
  appName: 'MUSICAL SYSTEM',
  eyebrow: 'DJ Mixer',
  intro:
    'Carga un MP3 en cada deck. Los dos pueden sonar a la vez. Pitch y tempo van juntos: no hay keylock. La salida es el dispositivo predeterminado.',
  activate: 'Activar audio',
  skipMixer: 'Saltar al crossfader',
  load: 'Cargar MP3',
  noTrack: 'Sin archivo',
  position: 'Posición',
  duration: 'Duración',
  volume: 'Volumen',
  cueHint: 'Sonando: vuelve al cue y pausa. En pausa, fuera del cue: lo fija. En el cue: mantén para preescuchar.',
  crossfader: 'Crossfader',
  crossfaderHelp: 'Izquierda es Deck A. Derecha es Deck B. El centro mezcla a potencia constante.',
  master: 'Master',
  masterHelp: 'Salida del dispositivo predeterminado.',
  bothPlaying: 'Deck A y Deck B están sonando a la vez.',
  eq: 'EQ',
  eqHelp: 'Graves, medios y agudos. 0 dB es plano. No es un kill.',
  waveform: 'Waveform',
  waveformEmpty: 'Carga un audio para ver la waveform. No se dibuja una forma falsa.',
  waveformWorking: 'Calculando waveform del audio decodificado…',
  pitch: 'Pitch / Tempo',
  pitchHelp: 'Cambia velocidad y tono juntos. No hay keylock.',
  bpm: 'BPM',
  bpmHelp: 'Etiqueta, estimado o manual. El efectivo es origen × velocidad, calculado, no medido en vivo.',
  bpmAnalyzing: 'Analizando BPM…',
  bpmMissing: 'No detectado',
  bpmSources: {
    manual: 'manual',
    detected: 'estimado',
    tag: 'etiqueta',
  },
  loop: 'Loop',
  loopHelp: 'El loop en beats usa el BPM de origen. Sin BPM solo vale marcar entrada y salida.',
  jog: 'Jog',
  jogHelp: 'En reproducción empuja el tempo. En pausa mueve la posición. No hay scratch.',
  spectrum: 'Espectro del master',
  meter: 'Nivel',
  sync: 'Sync',
  syncLock: 'Seguir',
  masterDeck: 'Maestro',
  context: {
    uninitialized: 'Audio inactivo',
    suspended: 'Audio suspendido',
    running: 'Audio activo',
    interrupted: 'Audio interrumpido',
    closed: 'Audio cerrado',
  },
  transport: {
    empty: 'Sin pista',
    loading: 'Cargando',
    ready: 'Listo',
    playing: 'Reproduciendo',
    preview: 'Preescucha',
    error: 'Error',
  },
  errors: {
    empty: 'El archivo está vacío.',
    'too-large': 'El archivo supera el límite de 100 MB. No se cargó.',
    unsupported: 'Este archivo no parece audio. Elige un MP3 u otro formato que el navegador pueda reproducir.',
    decode: 'No se pudo decodificar el audio. Puede estar dañado o usar un códec incompatible con este navegador.',
    read: 'No se pudo leer el archivo.',
    unsupportedContext: 'Este navegador no tiene Web Audio API. No hay salida de audio.',
    blocked: 'El navegador bloqueó el audio. Pulsa Activar audio y después Play.',
    interrupted: 'El navegador suspendió el audio. Pulsa Activar audio para continuar.',
    needTrack: 'Carga un MP3 en este deck antes de reproducir.',
    playback: 'No se pudo iniciar la reproducción.',
    needBpm: 'Falta BPM en el maestro o en este deck. El sync no inventa un tempo.',
    syncOutOfRange: 'El sync queda fuera del rango de pitch. Amplía el rango; no se recorta en secreto.',
    syncIsMaster: 'Este deck es el maestro. El sync mueve al otro deck.',
    bpmRange: 'El BPM manual tiene que estar entre 40 y 240.',
    loopNeedsPoints: 'Fija entrada y salida, con la salida después de la entrada, antes de activar el loop.',
    loopOrder: 'La salida del loop tiene que ser posterior a la entrada.',
    loopNoFit: 'Ese loop en beats no cabe desde la posición actual. No se acorta.',
    loopNeedsBpm: 'Sin BPM no se puede calcular un loop en beats.',
  },
} as const
