export const copy = {
  appName: 'MUSICAL SYSTEM',
  eyebrow: 'DJ Mixer',
  intro:
    'Carga un MP3 en cada deck. Los dos pueden sonar a la vez. Pitch y tempo van juntos: no hay keylock. La salida es el dispositivo predeterminado.',
  activate: 'Activar audio',
  skipMixer: 'Saltar al crossfader',
  load: 'Cargar MP3',
  noTrack: 'Sin archivo',
  position: 'Posición',
  duration: 'Duración',
  volume: 'Volumen',
  cueHint: 'Sonando: vuelve al cue y pausa. En pausa, fuera del cue: lo fija. En el cue: mantén para preescuchar.',
  crossfader: 'Crossfader',
  crossfaderHelp: 'Izquierda es Deck A. Derecha es Deck B. El centro mezcla a potencia constante.',
  master: 'Master',
  masterHelp: 'Salida del dispositivo predeterminado.',
  limiter: 'Limitador',
  limiterOn: 'Limitador activo',
  limiterOff: 'Limitador puenteado',
  limiterHelp: 'Es un compresor de dinámica en el master. Activo, reduce picos. Puenteado, la mezcla va directa a la salida.',
  bothPlaying: 'Deck A y Deck B están sonando a la vez.',
  eq: 'EQ',
  eqHelp: 'Graves, medios y agudos. 0 dB es plano. No es un kill.',
  waveform: 'Waveform',
  waveformEmpty: 'Carga un audio para ver la waveform. No se dibuja una forma falsa.',
  waveformWorking: 'Calculando waveform del audio decodificado…',
  pitch: 'Pitch / Tempo',
  pitchHelp: 'Cambia velocidad y tono juntos. No hay keylock.',
  bpm: 'BPM',
  bpmHelp: 'Etiqueta, estimado o manual. El efectivo es origen × velocidad, calculado, no medido en vivo.',
  bpmAnalyzing: 'Analizando BPM…',
  bpmMissing: 'No detectado',
  bpmSources: {
    manual: 'manual',
    detected: 'estimado',
    tag: 'etiqueta',
  },
  loop: 'Loop',
  loopHelp: 'El loop en beats usa el BPM de origen. Sin BPM solo vale marcar entrada y salida.',
  jog: 'Jog',
  jogHelp: 'En reproducción empuja el tempo. En pausa mueve la posición. No hay scratch.',
  spectrum: 'Espectro del master',
  meter: 'Nivel',
  sync: 'Sync',
  syncLock: 'Seguir',
  masterDeck: 'Maestro',
  context: {
    uninitialized: 'Audio inactivo',
    suspended: 'Audio suspendido',
    running: 'Audio activo',
    interrupted: 'Audio interrumpido',
    closed: 'Audio cerrado',
  },
  transport: {
    empty: 'Sin pista',
    loading: 'Cargando',
    ready: 'Listo',
    playing: 'Reproduciendo',
    preview: 'Preescucha',
    error: 'Error',
  },
  errors: {
    empty: 'El archivo está vacío.',
    'too-large': 'El archivo supera el límite de 100 MB. No se cargó.',
    unsupported: 'Este archivo no parece audio. Elige un MP3 u otro formato que el navegador pueda reproducir.',
    decode: 'No se pudo decodificar el audio. Puede estar dañado o usar un códec incompatible con este navegador.',
    read: 'No se pudo leer el archivo.',
    unsupportedContext: 'Este navegador no tiene Web Audio API. No hay salida de audio.',
    blocked: 'El navegador bloqueó el audio. Pulsa Activar audio y después Play.',
    interrupted: 'El navegador suspendió el audio. Pulsa Activar audio para continuar.',
    needTrack: 'Carga un MP3 en este deck antes de reproducir.',
    playback: 'No se pudo iniciar la reproducción.',
    needBpm: 'Falta BPM en el maestro o en este deck. El sync no inventa un tempo.',
    syncOutOfRange: 'El sync queda fuera del rango de pitch. Amplía el rango; no se recorta en secreto.',
    syncIsMaster: 'Este deck es el maestro. El sync mueve al otro deck.',
    bpmRange: 'El BPM manual tiene que estar entre 40 y 240.',
    loopNeedsPoints: 'Fija entrada y salida, con la salida después de la entrada, antes de activar el loop.',
    loopOrder: 'La salida del loop tiene que ser posterior a la entrada.',
    loopNoFit: 'Ese loop en beats no cabe desde la posición actual. No se acorta.',
    loopNeedsBpm: 'Sin BPM no se puede calcular un loop en beats.',
  },
  library: {
    toggle: 'Biblioteca',
    close: 'Cerrar biblioteca',
    title: 'Biblioteca local',
    help: 'Guarda el archivo original en este navegador. No lo recomprime y no incluye pistas de ejemplo.',
    import: 'Importar archivos',
    loading: 'Cargando biblioteca…',
    unsupported: 'Este navegador no puede guardar la biblioteca. Puedes cargar archivos en los decks, pero no quedan guardados.',
    empty: 'No hay archivos guardados.',
    emptyStorage: 'Todavía no hay archivos guardados.',
    storageOpfs: 'Archivos originales en el almacenamiento privado del navegador.',
    storageIdb: 'Archivos originales en IndexedDB. El navegador no dejó usar el almacenamiento de archivos.',
    storageMixed: 'Hay archivos en el almacenamiento de archivos y en IndexedDB.',
    duplicate: 'Ese archivo ya está en la biblioteca:',
    quota: 'No hay espacio suficiente o el navegador rechazó el guardado. El archivo no se añadió.',
    persistDenied: 'El navegador puede borrar estos archivos si falta espacio.',
    saveSettingsFailed: 'No se pudieron guardar los ajustes del mezclador.',
    settingsIgnored: 'Los ajustes guardados no se pudieron leer. Se usan los valores actuales.',
    bpmSaveFailed: 'El BPM no se pudo guardar en la biblioteca.',
    needFile: 'Ese deck no tiene un archivo de esta sesión para guardar. Cárgalo de nuevo desde el dispositivo.',
    missing: 'No se encontró el archivo guardado. Puede haberse borrado del almacenamiento.',
    deleteFailed: 'No se pudo borrar. La biblioteca no se modificó por completo.',
    emptyName: 'La playlist necesita un nombre.',
    pickPlaylist: 'Elige una playlist antes de añadir.',
    alreadyInPlaylist: 'Esa pista ya está en la playlist.',
    saveDeck: 'Guardar en biblioteca',
    onDeck: 'Cargado desde la biblioteca',
    restore: 'Cargar última selección',
    noLast: 'No hay una selección anterior para cargar.',
    restoreHelp: 'Solo carga al pulsar. No arranca el audio al abrir la página.',
    search: 'Buscar en la biblioteca',
    sort: 'Ordenar',
    direction: 'Dirección',
    ascending: 'Ascendente',
    descending: 'Descendente',
    allTracks: 'Todas las pistas',
    playlist: 'Playlist',
    newPlaylist: 'Nombre de la playlist',
    create: 'Crear playlist',
    rename: 'Renombrar',
    renameLabel: 'Nuevo nombre',
    deletePlaylist: 'Borrar playlist',
    deleteTrack: 'Borrar archivo',
    loadA: 'Cargar en A',
    loadB: 'Cargar en B',
    add: 'Añadir a la playlist',
    remove: 'Quitar de la playlist',
    up: 'Subir',
    down: 'Bajar',
    clear: 'Vaciar biblioteca',
    clearConfirm: '¿Borrar todos los archivos y playlists guardados en este navegador?',
    playlistOrder: 'El orden de esta playlist es el guardado. Subir y bajar lo cambian de verdad.',
    noMatches: 'Ningún archivo coincide con la búsqueda.',
    emptyPlaylist: 'Esta playlist no tiene pistas.',
    storedOpfs: 'Guardado en el almacenamiento de archivos',
    storedIdb: 'Guardado en IndexedDB',
    sorts: {
      addedAt: 'Fecha',
      title: 'Título',
      artist: 'Artista',
      bpm: 'BPM',
      duration: 'Duración',
    },
  },
} as const
