export const copy = {
  appName: 'MUSICAL SYSTEM',
  eyebrow: 'DJ Mixer',
  intro: 'Carga un MP3 en cada deck. Los dos pueden sonar a la vez. La salida es el dispositivo predeterminado.',
  activate: 'Activar audio',
  skipMixer: 'Saltar al crossfader',
  load: 'Cargar MP3',
  noTrack: 'Sin archivo',
  position: 'Posición',
  duration: 'Duración',
  volume: 'Volumen',
  cueHint: 'Sonando: vuelve al cue y pausa. En pausa, fuera del cue: lo fija. En el cue: mantén para preescuchar.',
  crossfader: 'Crossfader',
  crossfaderHelp: 'Izquierda es Deck A. Derecha es Deck B. El centro mezcla a potencia constante.',
  master: 'Master',
  masterHelp: 'Salida del dispositivo predeterminado.',
  bothPlaying: 'Deck A y Deck B están sonando a la vez.',
  eq: 'EQ',
  eqHelp: 'Graves, medios y agudos. 0 dB es plano. No es un kill.',
  context: {
    uninitialized: 'Audio inactivo',
    suspended: 'Audio suspendido',
    running: 'Audio activo',
    interrupted: 'Audio interrumpido',
    closed: 'Audio cerrado',
  },
  transport: {
    empty: 'Sin pista',
    loading: 'Cargando',
    ready: 'Listo',
    playing: 'Reproduciendo',
    preview: 'Preescucha',
    error: 'Error',
  },
  errors: {
    empty: 'El archivo está vacío.',
    'too-large': 'El archivo supera el límite de 100 MB. No se cargó.',
    unsupported: 'Este archivo no parece audio. Elige un MP3 u otro formato que el navegador pueda reproducir.',
    decode: 'No se pudo decodificar el audio. Puede estar dañado o usar un códec incompatible con este navegador.',
    read: 'No se pudo leer el archivo.',
    unsupportedContext: 'Este navegador no tiene Web Audio API. No hay salida de audio.',
    blocked: 'El navegador bloqueó el audio. Pulsa Activar audio y después Play.',
    interrupted: 'El navegador suspendió el audio. Pulsa Activar audio para continuar.',
    needTrack: 'Carga un MP3 en este deck antes de reproducir.',
    playback: 'No se pudo iniciar la reproducción.',
  },
} as const
